
version: 3
services:
    backend:
        build: .
        ports:
        -   "3000:3000"
        depends_on:
            -   database
    database:
        image: mysql
        ports:
        -   "3336: 3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: db
