apiVersion: v1
kind: Service
metadata:
    name: static-site-service
    annotations:
        service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
    labels:
        app: static-site
spec:
    type: LoadBalancer
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 3000
    selector:
        app: static-site
    sessionAffinity: None
