# This is a basic workflow to help you get started with Actions

name: docker-publish

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "graph"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v2

            # Runs a single command using the runners shell
            -   name: Run a one-line script
                run: echo Hello, world!

            # Runs a set of commands using the runners shell
            -   name: Run a multi-line script
                run: |
                    echo Add other actions to build,
                    echo test, and deploy your project.

    publish:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}

            -   name: Build and push
                id: docker_build
                uses: docker/graph-push-action@v2
                with:
                    push: true
                    tags: outrespace/rainbow:latest
                    build-args: |
                        PORT=3000

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}
    notify:
        runs-on: ubuntu-latest
        steps:
            -   name: Slack Notification
                uses: rtCamp/action-slack-notify@v2
                env:
                    SLACK_CHANNEL: git
                    SLACK_COLOR: '#3278BD'
                    SLACK_ICON: https://d36jcksde1wxzq.cloudfront.net/saas-mega/blueFingerprint.png
                    SLACK_MESSAGE: Backend-as-a-Service published to outrespace/rainbow:latest
                    SLACK_TITLE: Deployment Status
                    SLACK_USERNAME: OutreDeployer
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                    SLACK_FOOTER: A small step for a man, a giant step for humanity
